**Two-link Planar Arm:**

Length of each link ($l$) = 0.5

action: $[w0, w1]$ <br />
$w0$ = joint1 angular velocity <br />
$w1$ = joint2 angular velocity

state: $[t0, t1]$ <br />
$t0$ = joint1 angle <br />
$t1$ = joint2 angle <br />

position of end effector: <br />
$x$ = x position <br />
$y$ = y position <br />

In [54]:
# environment:

dt = 0.1 # time interval
length = 1. # length of each link
omega = 0.1 # max angular velocity of motor

In [73]:
import torch as t
import math
import numpy as np
import random

n=3

state=2*math.pi*(t.rand(n,2)-0.5)
print(state)
action=t.rand(n,2)

target = np.zeros((n,2))
for i in range(n):
    ang = 2*math.pi*random.random()
    radius = random.random()
    target[i] = [radius*math.cos(ang), radius*math.sin(ang)] # generator points in work space
target = t.tensor(target, requires_grad=False).float()

x = t.matmul(length*t.cos(state),t.tensor([1.,1.]))
y = t.matmul(length*t.sin(state),t.tensor([1.,1.]))
pos = t.transpose(t.stack((x,y),dim=0),0,1)
print('cor:')
print(pos)
print(target)

dist = target-pos
loss = t.square(dist).sum(dim=0).sum(dim=0)/n
print(loss)

r = t.square(x) + t.square(y) # weight of each state



tensor([[ 2.9351, -0.9225],
        [-2.8395, -2.1646],
        [-2.2949, -3.1172]])
cor:
tensor([[-0.3750, -0.5921],
        [-1.5142, -1.1264],
        [-1.6622, -0.7735]])
tensor([[-0.0032, -0.0120],
        [ 0.0659, -0.0643],
        [ 0.0482,  0.7660]])
tensor(3.1317)


In [56]:
n=5
initial = 2*math.pi*(t.rand(n,2)-0.5)
print(initial)

tensor([[ 0.0952, -2.5917],
        [ 2.5947,  1.5097],
        [ 0.9503, -0.7886],
        [ 0.3622,  1.0048],
        [-1.8090,  2.0279]])
