**Two-link Planar Arm:**

Length of each link ($l$) = 0.5

action: $[w0, w1]$ <br />
$w0$ = joint1 angular velocity <br />
$w1$ = joint2 angular velocity

state: $[t0, t1]$ <br />
$t0$ = joint1 angle <br />
$t1$ = joint2 angle <br />

position of end effector: <br />
$x$ = x position <br />
$y$ = y position <br />

In [14]:
# environment:

dt = 0.1 # time interval
length = 1. # length of each link
omega = 0.1 # max angular velocity of motor

In [15]:
import torch as t
import math
import numpy as np
import random

n=3

state=2*math.pi*(t.rand(n,4)-0.5)
print(state)
action=t.rand(n,2)

t.matmul
x = t.matmul(length*t.cos(state),t.tensor([1.,1.]))
y = t.matmul(length*t.sin(state),t.tensor([1.,1.]))

print('cor:')
print(t.transpose(dt*omega*action,0,1))
print(t.stack((x,y),dim=0))
print(t.stack(t.transpose(dt*omega*action,0,1), t.stack((x,y),dim=0)),dim=0)
state = state + t.cat((dt*omega*action, t.transpose(t.stack((x,y),dim=0),0,1)), 1)
print(state)





tensor([[ 0.9146,  1.2231],
        [ 1.8494,  2.4598],
        [ 1.3510, -0.6077]])
cor:
tensor([[0.0046, 0.0034, 0.0065],
        [0.0035, 0.0016, 0.0094]])
tensor([[ 0.9509, -1.0515,  1.0390],
        [ 1.7325,  1.5916,  0.4049]])


TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor

In [ ]:
n=5
initial = 2*math.pi*(t.rand(n,2)-0.5)
print(initial)

In [28]:
import torch as t
n=100
(t.rand(6)-0.5)*t.tensor([.1,.1,1.,.1,1.,.1])

tensor([ 0.0292, -0.0335, -0.1573,  0.0106, -0.1055, -0.0024])